name: Build
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  lint:
    name: "Lint"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: go
    steps:
      - name: Set up Go 1.16
        uses: actions/setup-go@v5
        with:
          go-version: 1.16

      - name: Check out code into the Go module directory
        uses: actions/checkout@v4

      - name: Get dependencies
        run: go get -v -t -d ./...

      - name: Get golangci-lint
        run: curl -sfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh| sh -s -- -b $(go env GOPATH)/bin v1.39.0

      - name: Lint
        run: $(go env GOPATH)/bin/golangci-lint run --timeout 3m0s ./...
